### PR TITLE
[WIP] Setting up Tests and learning how to configure conda and travis

### PR DESCRIPTION
**Pull request by bannanc**
Do the tests work now?

### CODE REVIEW

**Comment by davidlmobley** [comment]
Haha. I was thinking, "Wait, why is she asking GitHub whether the tests work?" ;)

**Comment by davidlmobley** [comment]
LMK if you need any help. It will be great to have another person in the group who knows how to set these up. :)

**Comment by bannanc** [comment]
Oh, yeah not really asking, I just wanted to open a PR to see if travis works now.

**Comment by bannanc** [comment]
@davidlmobley There are a million commits as I was trying to figure out how this worked, but I think it would be good for someone to review what I set up as tests. 

I checked for implicit hydrogens, which the test output on my desktop complains about, but None exist. It seems like adding tests here and in Forcefield for 3D conformers would be good, but I couldn't find a way to check for them with openeye. 

Similar issue raised in smarty here:
https://github.com/open-forcefield-group/smarty/issues/225

**Comment by bannanc** [comment]
Never mind the tests are passing, but it ran 0 tests so I'm still missing something.

**Comment by davidlmobley** [comment]
I'm a little confused. Where are the tests which are supposed to run on this? 

I think you're at the point where you think that this will work once the new smirnoff99Frosst is conda-installable, @bannanc ?

**Comment by bannanc** [comment]
@davidlmobley 
The tests are inside minidrugbank/tests/ 
I import openforcefield and use smirnoff99Frosst that is installed there, it shouldn't depend on smirnoff99Frosst being conda installable.

**Comment by davidlmobley** [comment]
@bannanc - did you intend to merge this? It says it's still failing tests and you still had [WIP] in the title.

**Comment by bannanc** [comment]
@davidlmobley 
I did the travis tests are still not working, but I had made changes to the mol2 files and I thought it would be important to get them into the Master branch. 
I can unmerge it if you think it would be better to keep that separate. I'll change the title.

**Comment by davidlmobley** [comment]
Oh, that sounds fine! I just didn't understand why it was merged without comment on here.

**Comment by bannanc** [comment]
Oh, I wrote a comment and then forgot to click the comment button the first time, sorry about the confusion.

**Pull request merged**
